// Categories
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const LOAD_CATEGORIES_BEGIN = "LOAD_CATEGORIES_BEGIN";
export const LOAD_CATEGORIES_END = "LOAD_CATEGORIES_END";
export const OPEN_CATEGORY_FORM = "OPEN_CATEGORY_FORM";

// Category Form
export const ADD_CATEGORY = "ADD_CATEGORY";
export const CANCEL_CATEGORY_FORM = "CANCEL_CATEGORY_FORM";
export const LOAD_ICONS_BEGIN = "LOAD_ICONS_BEGIN";
export const LOAD_ICONS_END = "LOAD_ICONS_END";
